// CricHeroes Impact Metric UI
// Data source: data/final_scores.json (generated by your Python pipeline)

let PLAYERS = [];
let dashReady = false;
let chartInnings = null;
let chartMoment = null;

document.addEventListener("DOMContentLoaded", async () => {
  const lpBtn = document.getElementById("lp-btn");
  if (lpBtn) lpBtn.disabled = true;

  try {
    const res = await fetch("data/final_scores.json", { cache: "no-store" });
    if (!res.ok) throw new Error(`Failed to load final_scores.json (${res.status})`);
    const raw = await res.json();

    PLAYERS = (Array.isArray(raw) ? raw : [])
      .map(normalizePlayer)
      .filter((p) => !!p.name)
      .sort((a, b) => (b.impact_score ?? 0) - (a.impact_score ?? 0));

    if (lpBtn) lpBtn.disabled = false;
    initLanding();
  } catch (err) {
    initLanding(String(err?.message || err));
  }
});

function normalizePlayer(p) {
  const name = (p?.name ?? p?.["Player Name"] ?? "").toString().trim();
  const impact_score = toNumber(p?.impact_score) ?? 0;
  const matches_played =
    toNumber(p?.matches_played) ??
    toNumber(p?.total_innings) ??
    0;
  const trend = (p?.trend ?? "stable").toString().trim() || "stable";
  const last_10_innings = Array.isArray(p?.last_10_innings)
    ? p.last_10_innings.map((v) => toNumber(v) ?? 0).slice(0, 10)
    : [];

  return { name, impact_score, matches_played, trend, last_10_innings };
}

function toNumber(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function clamp(n, a, b) {
  return Math.max(a, Math.min(b, n));
}

function norm(s) {
  return (s || "").toString().trim().toLowerCase();
}

function findPlayerBest(query) {
  const q = norm(query);
  if (!PLAYERS.length) return null;
  if (!q) return PLAYERS[0];

  const exact = PLAYERS.find((p) => norm(p.name) === q);
  if (exact) return exact;

  const starts = PLAYERS.find((p) => norm(p.name).startsWith(q));
  if (starts) return starts;

  const contains = PLAYERS.find((p) => norm(p.name).includes(q));
  if (contains) return contains;

  return null;
}

function scoreColor(v) {
  if (v >= 80) return "#4c9eff";
  if (v >= 60) return "#22c55e";
  if (v >= 40) return "#f5c518";
  if (v >= 20) return "#ff6b35";
  return "#ef4444";
}

function category(v) {
  if (v >= 75) return "Match Winner";
  if (v >= 60) return "Impact Player";
  if (v >= 40) return "Average Contributor";
  return "Needs Form";
}

function catColor(v) {
  const c = category(v);
  if (c === "Match Winner" || c === "Impact Player") return "#22c55e";
  if (c === "Average Contributor") return "#f5c518";
  return "#ef4444";
}

function trendArrow(t) {
  const l = norm(t);
  if (l === "surging") return "↑↑";
  if (l === "rising") return "↑";
  if (l === "falling") return "↓";
  if (l === "plummeting") return "↓↓";
  return "→";
}

function dotColor(v) {
  if (v >= 70) return "#22c55e";
  if (v >= 40) return "#f5c518";
  return "#ef4444";
}

function numberGradientVars(baseHex) {
  // Blend "tier" color into brand blue for premium gradient numbers.
  return {
    ng1: baseHex,
    ng2: "#3b82f6",
  };
}

function initLanding(errorMessage) {
  const lpInput = document.getElementById("lp-input");
  const lpBtn = document.getElementById("lp-btn");
  const lpSugs = document.getElementById("lp-sugs");
  const lpErr = document.getElementById("lp-err");
  const lpBox = document.getElementById("lp-box");

  if (!lpInput || !lpBtn || !lpSugs || !lpErr || !lpBox) return;

  if (errorMessage) {
    lpErr.textContent = `Could not load data: ${errorMessage}`;
    lpErr.style.display = "block";
    lpBtn.disabled = true;
  }

  lpInput.addEventListener("input", () => {
    const q = norm(lpInput.value);
    lpErr.style.display = "none";
    if (!q) {
      lpSugs.style.display = "none";
      return;
    }

    const matches = PLAYERS.filter((p) => norm(p.name).includes(q)).slice(0, 7);
    if (!matches.length) {
      lpSugs.style.display = "none";
      return;
    }

    lpSugs.innerHTML = matches
      .map(
        (p) => `
        <div class="sug" data-name="${escapeHtml(p.name)}">
          <span class="sug-name">${escapeHtml(p.name)}</span>
          <span class="sug-meta">Impact: ${p.impact_score.toFixed(1)} · ${p.matches_played} matches · ${escapeHtml(p.trend)}</span>
        </div>
      `
      )
      .join("");
    lpSugs.style.display = "block";
  });

  lpSugs.addEventListener("click", (e) => {
    const item = e.target.closest(".sug");
    if (!item) return;
    lpInput.value = item.dataset.name;
    lpSugs.style.display = "none";
    goToDash(item.dataset.name);
  });

  document.addEventListener("click", (e) => {
    if (!e.target.closest(".lp-wrap")) lpSugs.style.display = "none";
  });

  const tryLaunch = () => {
    const q = lpInput.value.trim();
    if (!q) return;

    const found = findPlayerBest(q);
    if (found) {
      goToDash(found.name);
      return;
    }

    lpBox.classList.remove("lp-shake");
    void lpBox.offsetWidth;
    lpBox.classList.add("lp-shake");
    lpErr.style.display = "block";
  };

  lpBtn.addEventListener("click", tryLaunch);
  lpInput.addEventListener("keypress", (e) => {
    if (e.key === "Enter") tryLaunch();
  });

  // Back to home
  const navBack = document.getElementById("nav-back");
  if (navBack) {
    navBack.addEventListener("click", () => {
      document.getElementById("page-dash")?.classList.remove("show");
      document.getElementById("page-landing")?.classList.remove("gone");

      const loader = document.getElementById("loader");
      if (loader) {
        loader.style.display = "flex";
        loader.style.opacity = "1";
      }

      lpInput.value = "";
      lpErr.style.display = "none";
      lpSugs.style.display = "none";

      try {
        window.scrollTo({ top: 0, behavior: "smooth" });
      } catch {
        window.scrollTo(0, 0);
      }
    });
  }
}

function goToDash(playerName) {
  const landing = document.getElementById("page-landing");
  const dash = document.getElementById("page-dash");
  const loader = document.getElementById("loader");

  if (!landing || !dash || !loader) return;

  landing.classList.add("gone");
  dash.classList.add("show");

  // Smooth loader phase
  loader.style.display = "flex";
  loader.style.opacity = "1";

  // Delay for premium feel (and to mimic analysis)
  setTimeout(() => {
    loader.style.opacity = "0";
    setTimeout(() => {
      loader.style.display = "none";
    }, 800);

    initDash();

    const target = findPlayerBest(playerName) || PLAYERS[0];
    if (target) {
      loadPlayer(target);
      const ds = document.getElementById("dsearch");
      if (ds) ds.value = target.name;
    }

    try {
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch {
      window.scrollTo(0, 0);
    }
  }, 2000);
}

function initDash() {
  if (dashReady) return;
  dashReady = true;

  // Populate comparison selects once
  const selA = document.getElementById("sel-a");
  const selB = document.getElementById("sel-b");
  if (selA && selB) {
    for (const p of PLAYERS) {
      selA.appendChild(new Option(p.name, p.name));
      selB.appendChild(new Option(p.name, p.name));
    }
    selA.addEventListener("change", runCompare);
    selB.addEventListener("change", runCompare);
  }

  // Dashboard search
  const ds = document.getElementById("dsearch");
  const dBtn = document.getElementById("dbtn");
  const dd = document.getElementById("dd");

  if (!ds || !dBtn || !dd) return;

  ds.addEventListener("input", () => {
    const q = norm(ds.value);
    if (!q) {
      dd.style.display = "none";
      return;
    }

    const m = PLAYERS.filter((p) => norm(p.name).includes(q)).slice(0, 6);
    if (!m.length) {
      dd.style.display = "none";
      return;
    }

    dd.innerHTML = m
      .map(
        (p) => `
        <div class="dd-item" data-name="${escapeHtml(p.name)}">
          <span class="dd-name">${escapeHtml(p.name)}</span>
          <span class="dd-meta">Impact: ${p.impact_score.toFixed(1)} · ${p.matches_played} matches</span>
        </div>
      `
      )
      .join("");
    dd.style.display = "block";
  });

  dd.addEventListener("click", (e) => {
    const item = e.target.closest(".dd-item");
    if (!item) return;
    const p = findPlayerBest(item.dataset.name);
    if (!p) return;
    ds.value = p.name;
    dd.style.display = "none";
    loadPlayer(p);
  });

  document.addEventListener("click", (e) => {
    if (!e.target.closest(".search-bar")) dd.style.display = "none";
  });

  const doSearch = () => {
    const p = findPlayerBest(ds.value);
    if (!p) return;
    ds.value = p.name;
    dd.style.display = "none";
    loadPlayer(p);
  };

  dBtn.addEventListener("click", doSearch);
  ds.addEventListener("keypress", (e) => {
    if (e.key === "Enter") doSearch();
  });
}

function loadPlayer(p) {
  const grid = document.getElementById("grid");
  if (!grid) return;

  grid.style.opacity = "0";
  grid.style.transform = "translateY(-10px)";

  setTimeout(() => {
    renderPlayerCard(p);
    renderGauge(p.impact_score);
    renderInningsChart(p.last_10_innings || []);
    renderMomentumChart(p.last_10_innings || []);
    grid.style.opacity = "1";
    grid.style.transform = "translateY(0)";
  }, 350);
}

function renderPlayerCard(p) {
  const el = document.getElementById("card-player");
  if (!el) return;

  const score = clamp(toNumber(p.impact_score) ?? 0, 0, 100);
  const tier = scoreColor(score);
  const grad = numberGradientVars(tier);

  const innings = Array.isArray(p.last_10_innings) ? p.last_10_innings : [];
  const best = innings.length ? Math.max(...innings).toFixed(2) : "—";

  const mean = innings.length ? innings.reduce((a, b) => a + b, 0) / innings.length : 0;
  const sd = innings.length
    ? Math.sqrt(innings.reduce((a, v) => a + Math.pow(v - mean, 2), 0) / innings.length)
    : 0;
  const cons = sd >= 20 ? "High" : sd >= 10 ? "Med" : "Low";

  const clutch = score >= 80 ? `<div class="clutch-badge">🔥 CLUTCH PLAYER</div>` : "";
  const dots = innings
    .map(
      (v, i) =>
        `<span class="dot" style="background:${dotColor(v)};margin-right:${i === innings.length - 1 ? 0 : 3}px;" title="${Number(v).toFixed(1)}"></span>`
    )
    .join("");

  el.innerHTML = `
    <h2>Player Profile</h2>
    <div class="big-score num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};">${score.toFixed(0)}</div>
    <div class="score-sub">/ 100 IMPACT SCORE</div>

    <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-bottom:6px;position:relative;z-index:1;">
      <div class="pname">${escapeHtml(p.name)}</div>
      ${clutch}
    </div>
    <div class="pill" style="background:${catColor(score)}">${escapeHtml(category(score))}</div>

    <div class="stats-grid">
      <div class="stat-box">
        <div class="stat-lbl">MATCHES PLAYED</div>
        <div class="stat-val num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};">${Number(p.matches_played || 0)}</div>
      </div>
      <div class="stat-box">
        <div class="stat-lbl">TREND</div>
        <div class="stat-val">${escapeHtml(trendArrow(p.trend))} ${escapeHtml(p.trend || "stable")}</div>
      </div>
      <div class="stat-box">
        <div class="stat-lbl">BEST INNING</div>
        <div class="stat-val num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};">${best}</div>
      </div>
      <div class="stat-box">
        <div class="stat-lbl">CONSISTENCY</div>
        <div class="stat-val">${escapeHtml(cons)}</div>
      </div>
    </div>

    <div class="form-lbl">LAST 10 FORM</div>
    <div style="position:relative;z-index:1;">${dots || `<span style="color:var(--muted);font-size:.9rem;">No innings data</span>`}</div>
  `;
}

function renderGauge(rawScore) {
  const el = document.getElementById("card-gauge");
  if (!el) return;

  const score = clamp(toNumber(rawScore) ?? 0, 0, 100);
  const tier = scoreColor(score);
  const grad = numberGradientVars(tier);

  const cx = 150, cy = 140, r = 110;
  const circ = Math.PI * r;
  const offset = circ * (1 - score / 100);
  // Match earlier working gauge behaviour: sweep from -90° to +90°
  const angle = (score / 100) * 180 - 90;

  const ticks = [
    { v: 0, c: "#ef4444" },
    { v: 25, c: "#ef4444" },
    { v: 50, c: "#f5c518" },
    { v: 75, c: "#22c55e" },
    { v: 100, c: "#4c9eff" },
  ]
    .map((t) => {
      const deg = -180 + (t.v / 100) * 180;
      const rad = (deg * Math.PI) / 180;
      const x1 = cx + (r - 8) * Math.cos(rad);
      const y1 = cy + (r - 8) * Math.sin(rad);
      const x2 = cx + (r + 6) * Math.cos(rad);
      const y2 = cy + (r + 6) * Math.sin(rad);
      return `<line x1="${x1.toFixed(1)}" y1="${y1.toFixed(1)}" x2="${x2.toFixed(1)}" y2="${y2.toFixed(
        1
      )}" stroke="${t.c}" stroke-width="2.5" stroke-linecap="round"/>`;
    })
    .join("");

  el.innerHTML = `
    <h2>Impact Score</h2>
    <div style="position:relative;width:300px;height:170px;margin:1.5rem auto 1rem;z-index:1;">
      <svg viewBox="0 0 300 170" width="300" height="170">
        <path d="M40 140 A110 110 0 0 1 260 140" fill="none" stroke="rgba(15,23,42,.9)" stroke-width="18" stroke-linecap="round"/>
        <path class="g-arc" d="M40 140 A110 110 0 0 1 260 140" fill="none" stroke="${tier}" stroke-width="18" stroke-linecap="round"
          stroke-dasharray="${circ}" stroke-dashoffset="${circ}" style="transition:stroke-dashoffset 1.6s ease"/>
        ${ticks}
        <text x="40" y="158" text-anchor="middle" fill="#6b7280" font-size="9" font-family="monospace">0</text>
        <text x="150" y="158" text-anchor="middle" fill="#6b7280" font-size="9" font-family="monospace">50</text>
        <text x="260" y="158" text-anchor="middle" fill="#6b7280" font-size="9" font-family="monospace">100</text>
        <g class="g-needle" style="transform-origin:${cx}px ${cy}px;transform:rotate(-90deg);transition:transform 1.8s cubic-bezier(.34,1.56,.64,1)">
          <line x1="${cx}" y1="${cy}" x2="${cx}" y2="${cy - r + 20}" stroke="#fff" stroke-width="3" stroke-linecap="round"/>
          <circle cx="${cx}" cy="${cy}" r="8" fill="#fff"/>
          <circle cx="${cx}" cy="${cy - r + 20}" r="4" fill="${tier}"/>
        </g>
      </svg>
      <div style="position:absolute;bottom:-14px;width:100%;text-align:center;">
        <span class="g-num num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};font-size:2.7rem;font-weight:700;letter-spacing:.06em;">0</span>
      </div>
    </div>

    <div style="margin-top:2rem;position:relative;z-index:1;">
      <div style="height:3px;border-radius:999px;background:linear-gradient(90deg,#ef4444,#f5c518 50%,#22c55e 75%,#4c9eff);position:relative;margin:.5rem 0 1.2rem;box-shadow:0 0 14px rgba(15,23,42,.9);">
        <div style="position:absolute;top:50%;left:${score}%;transform:translate(-50%,-50%);width:8px;height:8px;border-radius:50%;background:${tier};box-shadow:0 0 10px ${tier};border:1px solid rgba(15,23,42,.9);"></div>
      </div>
      <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:.75rem;text-align:left;">
        ${miniMetric("PERFORMANCE", score, grad)}
        ${miniMetric("CONTEXT", score * 1.1, grad)}
        ${miniMetric("PRESSURE PI", score * 0.9, grad)}
      </div>
    </div>
  `;

  requestAnimationFrame(() => {
    setTimeout(() => {
      const arc = el.querySelector(".g-arc");
      const needle = el.querySelector(".g-needle");
      const num = el.querySelector(".g-num");
      if (arc) arc.style.strokeDashoffset = String(offset);
      if (needle) needle.style.transform = `rotate(${angle}deg)`;

      let cur = 0;
      const step = score / (1500 / 20);
      const t = setInterval(() => {
        cur = Math.min(cur + step, score);
        if (num) num.textContent = cur.toFixed(1);
        if (cur >= score) clearInterval(t);
      }, 20);
    }, 60);
  });
}

function miniMetric(label, value, grad) {
  const v = clamp(value, 0, 120);
  return `
    <div>
      <div style="font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);margin-bottom:2px;">${escapeHtml(
        label
      )}</div>
      <div class="num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};font-size:1.4rem;font-weight:700;">${v.toFixed(
        1
      )}</div>
    </div>
  `;
}

function renderInningsChart(data) {
  const el = document.getElementById("card-innings");
  if (!el) return;

  const arr = Array.isArray(data) ? data.slice(0, 10).map((v) => toNumber(v) ?? 0) : [];

  el.innerHTML = `
    <h2>Impact per Inning</h2>
    <div style="position:relative;width:100%;height:280px;margin-top:1rem;z-index:1;">
      <canvas id="cv-innings"></canvas>
    </div>
  `;

  if (chartInnings) {
    chartInnings.destroy();
    chartInnings = null;
  }

  const canvas = document.getElementById("cv-innings");
  if (!canvas || typeof Chart === "undefined") return;

  const ctx = canvas.getContext("2d");
  const bg = arr.map((v) =>
    v >= 100 ? "rgba(76,158,255,.75)" : v >= 50 ? "rgba(34,197,94,.75)" : v >= 20 ? "rgba(245,197,24,.75)" : "rgba(239,68,68,.75)"
  );
  const bd = arr.map((v) => (v >= 100 ? "#4c9eff" : v >= 50 ? "#22c55e" : v >= 20 ? "#f5c518" : "#ef4444"));
  const max = arr.length ? Math.max(...arr) : 0;
  const yMax = max > 100 ? Math.ceil(max / 20) * 20 + 10 : 110;

  chartInnings = new Chart(ctx, {
    type: "bar",
    data: {
      labels: arr.map((_, i) => `${i + 1}`),
      datasets: [
        {
          type: "bar",
          data: arr,
          backgroundColor: bg,
          borderColor: bd,
          borderWidth: 1.5,
          borderRadius: 4,
        },
        {
          type: "line",
          data: arr.map(() => 50),
          borderColor: "rgba(255,255,255,.18)",
          borderWidth: 1.5,
          borderDash: [6, 4],
          pointRadius: 0,
          hitRadius: 0,
          hoverRadius: 0,
        },
      ],
    },
    options: {
      animation: { duration: 1800, easing: "easeOutQuart" },
      maintainAspectRatio: false,
      responsive: true,
      layout: { padding: { right: 16, top: 8 } },
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: "#0d1017",
          borderColor: "rgba(255,255,255,.1)",
          borderWidth: 1,
          callbacks: {
            label: (c) => `Inning ${c.dataIndex + 1}  —  ${Number(c.parsed.y).toFixed(1)}`,
          },
        },
      },
      scales: {
        y: {
          beginAtZero: true,
          suggestedMax: yMax,
          title: { display: true, text: "IMPACT SCORE", color: "#4a5870", font: { size: 10 } },
          ticks: { color: "#4a5870" },
          grid: { color: "rgba(148,163,184,.12)" },
        },
        x: {
          title: { display: true, text: "INNINGS (OLDEST → NEWEST)", color: "#4a5870", font: { size: 10 } },
          ticks: { color: "#4a5870" },
          grid: { display: false },
        },
      },
    },
  });
}

function renderMomentumChart(data) {
  const el = document.getElementById("card-moment");
  if (!el) return;

  const arr = Array.isArray(data) ? data.slice(0, 10).map((v) => toNumber(v) ?? 0) : [];
  const sma = arr.map((v, i, a) => {
    const s = Math.max(0, i - 2);
    const avg = a.slice(s, i + 1).reduce((x, y) => x + y, 0) / (i - s + 1);
    return Number(avg.toFixed(2));
  });

  el.innerHTML = `
    <h2>Impact Momentum (3-Match SMA)</h2>
    <div style="position:relative;width:100%;height:280px;margin-top:1rem;z-index:1;">
      <canvas id="cv-moment"></canvas>
    </div>
  `;

  if (chartMoment) {
    chartMoment.destroy();
    chartMoment = null;
  }

  const canvas = document.getElementById("cv-moment");
  if (!canvas || typeof Chart === "undefined") return;

  const ctx = canvas.getContext("2d");
  const gLine = ctx.createLinearGradient(0, 0, canvas.offsetWidth || 400, 0);
  gLine.addColorStop(0, "#ef4444");
  gLine.addColorStop(1, "#22c55e");
  const gFill = ctx.createLinearGradient(0, 0, 0, 300);
  gFill.addColorStop(0, "rgba(34,197,94,.3)");
  gFill.addColorStop(1, "rgba(34,197,94,0)");

  chartMoment = new Chart(ctx, {
    type: "line",
    data: {
      labels: arr.map((_, i) => `${i + 1}`),
      datasets: [
        {
          data: sma,
          borderColor: gLine,
          borderWidth: 3,
          tension: 0.38,
          fill: true,
          backgroundColor: gFill,
          pointRadius: 5,
          pointBackgroundColor: "#fff",
          pointBorderColor: "#22c55e",
          pointBorderWidth: 2,
        },
      ],
    },
    options: {
      animation: { duration: 2200, easing: "easeInOutBack" },
      maintainAspectRatio: false,
      responsive: true,
      layout: { padding: { right: 16, top: 8 } },
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: "#0d1017",
          borderColor: "rgba(255,255,255,.1)",
          borderWidth: 1,
          callbacks: {
            label: (c) => {
              const i = c.dataIndex;
              const cur = sma[i];
              const prev = i > 0 ? sma[i - 1] : cur;
              const dir = cur > prev ? "↑ Rising" : cur < prev ? "↓ Falling" : "→ Stable";
              return `SMA: ${cur.toFixed(2)}  ${dir}`;
            },
          },
        },
      },
      scales: {
        y: { beginAtZero: true, ticks: { color: "#4a5870" }, grid: { color: "rgba(148,163,184,.12)" } },
        x: { ticks: { color: "#4a5870" }, grid: { display: false } },
      },
    },
  });
}

function runCompare() {
  const aName = document.getElementById("sel-a")?.value || "";
  const bName = document.getElementById("sel-b")?.value || "";
  const wrap = document.getElementById("cmp-wrap");
  if (!wrap) return;

  // Clear when one side not selected
  if (!aName || !bName) {
    wrap.innerHTML = "";
    return;
  }

  // If same player selected on both sides, ask user to pick different players
  if (norm(aName) === norm(bName)) {
    wrap.innerHTML = `
      <div style="grid-column:1/-1;padding:1rem 1.2rem;border-radius:10px;background:rgba(15,23,42,.9);border:1px solid var(--border);color:var(--muted);font-size:.9rem;">
        Please select <strong>two different players</strong> to compare impact.
      </div>
    `;
    return;
  }

  const a = findPlayerBest(aName);
  const b = findPlayerBest(bName);
  if (!a || !b) {
    wrap.innerHTML = "";
    return;
  }

  const iA = clamp(a.impact_score ?? 0, 0, 100);
  const iB = clamp(b.impact_score ?? 0, 0, 100);
  const winner = iA > iB ? a : iA < iB ? b : null;

  const statsOf = (arr) => {
    if (!arr?.length) return { best: "—", worst: "—", avg: "—" };
    const best = Math.max(...arr);
    const worst = Math.min(...arr);
    const avg = arr.reduce((x, y) => x + y, 0) / arr.length;
    return { best: best.toFixed(1), worst: worst.toFixed(1), avg: avg.toFixed(1) };
  };

  const sA = statsOf(a.last_10_innings);
  const sB = statsOf(b.last_10_innings);

  const hi = (va, vb) => {
    const n1 = toNumber(va);
    const n2 = toNumber(vb);
    if (n1 === null || n2 === null || n1 === n2) return ["var(--text)", "var(--text)"];
    return n1 > n2 ? ["#22c55e", "#ef4444"] : ["#ef4444", "#22c55e"];
  };

  const [icA, icB] = hi(iA, iB);
  const [mcA, mcB] = hi(a.matches_played, b.matches_played);
  const [bcA, bcB] = hi(sA.best, sB.best);
  const [acA, acB] = hi(sA.avg, sB.avg);

  const dotsHtml = (arr) =>
    (arr || [])
      .slice(0, 10)
      .map((v, i) => `<span class="dot" style="background:${dotColor(v)};margin-right:${i === 9 ? 0 : 3}px;"></span>`)
      .join("");

  const card = (p, imp, col, mat, mc, st, bc, ac, isWin) => {
    const tier = scoreColor(imp);
    const grad = numberGradientVars(tier);
    return `
      <div class="cmp-card ${isWin ? "winner" : ""}">
        <h3 style="text-transform:uppercase;letter-spacing:.08em;text-align:center;font-size:1.4rem;margin-bottom:.5rem;position:relative;z-index:1;">${escapeHtml(
          p.name
        )}</h3>
        <div style="text-align:center;margin-bottom:.5rem;position:relative;z-index:1;">
          <span class="num-gradient" style="--ng1:${grad.ng1};--ng2:${grad.ng2};font-size:3rem;font-weight:700;">${Number(imp).toFixed(
            1
          )}</span>
        </div>
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:.8rem;position:relative;z-index:1;">
          <span class="pill" style="background:${catColor(imp)};font-size:.65rem;">${escapeHtml(category(imp))}</span>
          <span style="font-size:.85rem;color:var(--muted);">${escapeHtml(trendArrow(p.trend))} ${escapeHtml(
            p.trend || "stable"
          )}</span>
        </div>
        ${[
          ["Matches Played", mat, mc],
          ["Best (Last 10)", st.best, bc],
          ["Avg (Last 10)", st.avg, ac],
          ["Worst (Last 10)", st.worst, "var(--text)"],
        ]
          .map(
            ([lbl, val, c], i) => `
            <div style="display:flex;justify-content:space-between;padding:.35rem .5rem;background:${
              i % 2 ? "transparent" : "rgba(0,0,0,.2)"
            };border-radius:4px;margin-bottom:2px;position:relative;z-index:1;">
              <span style="font-size:.72rem;color:var(--muted);">${escapeHtml(lbl)}</span>
              <span style="font-size:.85rem;font-weight:700;color:${c};">${escapeHtml(String(val))}</span>
            </div>
          `
          )
          .join("")}
        <div style="margin-top:.6rem;position:relative;z-index:1;">
          <div class="form-lbl">LAST 10 FORM</div>
          <div>${dotsHtml(p.last_10_innings)}</div>
        </div>
      </div>
    `;
  };

  const diff = Math.abs(iA - iB).toFixed(1);
  const verdict = winner
    ? `🏆 ${winner.name} leads by ${diff} impact points — ${category(winner.impact_score)} vs ${category(winner === a ? iB : iA)}`
    : `🤝 Both players are evenly matched`;

  wrap.innerHTML = `
    <div style="grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:1rem;position:relative;z-index:1;">
      <span style="font-size:1.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${escapeHtml(
        a.name
      )}</span>
      <span style="font-size:2.2rem;font-weight:900;color:#ef4444;letter-spacing:.15em;flex:0 0 auto;">VS</span>
      <span style="font-size:1.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em;text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">${escapeHtml(
        b.name
      )}</span>
    </div>
    ${card(a, iA, icA, a.matches_played, mcA, sA, bcA, acA, winner === a)}
    ${card(b, iB, icB, b.matches_played, mcB, sB, bcB, acB, winner === b)}
    <div style="grid-column:1/-1;margin-top:1rem;padding:.8rem 1rem;background:rgba(6,8,16,.9);border-radius:10px;border-left:4px solid var(--green);font-weight:600;font-size:.95rem;position:relative;z-index:1;">
      ${escapeHtml(verdict)}
    </div>
  `;
}

function escapeHtml(s) {
  return (s ?? "")
    .toString()
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

